### ISSUE TITLE
Checksum errors on server render

### ISSUE THREAD

**Issue by hoegrammer** [commissure/redbox-react#21] opened 2015-09-15 10:36 UTC
When rendering an error using server side rendering with v1.0.4, React reports a checksum mismatch between what is rendered by the server and by the client. Example:

```
(client) v40.1.3.1">Torna all&#x27;elenco</span><
(server) v40.1.3.1">Torna all'elenco</span></a><d 
```

On the server the apostrophe has not been rendered as a HTML entity but on the client it has. I've also seen it happen with space vs `&nbsp;`

**Comment by davidpfahler** [comment] 2015-09-25 05:32
@hoegrammer Do you have any idea why this would happen? My first reaction would be to say that this cannot possibly be a redbox issue, but, of course, I might be wrong. I haven't played around with server-side rendering and redbox. I would also be curious why you would used redbox with server-side rendering, as redbox is clearly only for dev.

**Comment by hoegrammer** [comment] 2015-09-25 08:25
@davidpfahler  The issue could be with the react-transform or react-transform-catch-errors plugin. I'll investigate more when I get a chance.

I'm surprised you don't expect people to use it in server side rendering - I had read that as being the point of 1.0.4 (see https://github.com/KeywordBrain/redbox-react/issues/11)

**Comment by davidpfahler** [comment] 2015-09-25 11:45
@hoegrammer I definitely want server side rendering to work. I was just curious.

**Comment by glenjamin** [comment] 2015-09-25 12:49
The main reason for using server side rendering in dev is so we know it works, the main reason for using redbox on sever in dev is for when it doesn't.

Perhaps we might be better off just dumping a stack trace on server errors after all - as not every server error would also reproduce on the client.

(I work with @hoegrammer)

**Comment by gaearon** [comment] 2015-12-25 16:08
I think I never intended React Transform to be used on the server. Is there a benefit to having redbox on server as opposed to regular errors? You don't get hot reloading anyway.

**Comment by glenjamin** [comment] 2015-12-28 09:16
What do you mean by a regular error?

In dev, when there's a server error I'll want a successful react render so that when I fix it, the page still hot reloads into a fixed state.

In prod I think I'd want to record the error and attempt to render the rest of the page with that component boxed out - as it might not be critical. Component systems which do this are very resilient.

**Comment by davidpfahler** [comment] 2016-06-17 22:25
@glenjamin @hoegrammer @gaearon Do you know if this is still an issue with RHL 3 (aka the future)?

**Comment by mxlje** [comment] 2016-08-09 16:07
Closing because there hasn’t been any activity on this in a while. Please reopen if somebody still having problems.

**Closed** 2016-08-09 16:06 UTC
